# ╭──────────────────────────────────────────────────────────────╮
# │ Sunflower • Hyprland • Zsh • Neovim                          │
# ╰──────────────────────────────────────────────────────────────╯

include ~/.config/sunflower/active-kitty.conf

# ─────────────────────────────────────────────────────────────
# FONT
# ─────────────────────────────────────────────────────────────

bold_font        auto
italic_font      auto
bold_italic_font auto

# Window layout
cursor_shape                 block
shell_integration            disabled
# cursor_trail                 1
# cursor_trail_decay           0.05 0.25
# cursor_trail_start_threshold 5
remember_window_size  yes
initial_window_width  900
initial_window_height 600
window_padding_width  10
hide_window_decorations no

dynamic_background_opacity yes

background_blur 0

# Tab bar
tab_bar_edge bottom
tab_bar_style powerline
tab_powerline_style slanted

# Advanced
shell .
editor .
allow_remote_control socket-only
listen_on unix:$XDG_RUNTIME_DIR/kitty-{kitty_pid}
update_check_interval 0

repaint_delay 6
input_delay 1
sync_to_monitor yes

# Bell
enable_audio_bell no
visual_bell_duration 0.0

# Mouse
mouse_hide_wait 3.0
url_style curly
open_url_with default
copy_on_select yes
confirm_os_window_close 0

map super+shift+p send_text normal,application tmux.sh\r
